# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Workspace 1 - Task Management & Notes
exec-once = [workspace 1] uwsm app -- obsidian

# Workspace 2 - Development
exec-once = [workspace 2] uwsm app -- code
exec-once = [workspace 2] uwsm app -- ghostty 

# Workspace 3 - Media & Entertainment
exec-once = [workspace 3] uwsm app -- chromium --new-window --ozone-platform=wayland
exec-once = [workspace 3] uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://copilot.microsoft.com/"

# Workspace 4 - Research & Reading


# Workspace 5 - Communication
exec-once = [workspace 5] uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://mail.google.com/mail/u/0/"
exec-once = [workspace 5] uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://www.facebook.com/messages/t/"
